title: timmywiff
author: Tim Wiffen
# email: your-email@domain.com
description: Dev, dev, dev...

# social links
twitter_username: timmywiff
github_username:  timmywiff
# rss: rss
# instagram_username: jekyll
# linkedin_username: jekyll
# youtube_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%e %B %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
